In [22]:
import numpy as np
from figer_preprocessing import *
import pickle

In [19]:
from numpy.linalg import inv

In [25]:
with open('outputs/FIGER/ent_to_ind.bin', 'rb') as f:
    ent_to_ind = pickle.load(f)

with open('outputs/FIGER/type_to_ind.bin', 'rb') as f:
    type_to_ind = pickle.load(f)

In [9]:
targets[targets==0] = -1

In [10]:
targets = torch.tensor(targets, dtype=torch.float)
type_adj = batched_target_to_adj(targets)

In [11]:
type_adj = torch.sum(type_adj, dim=0)

In [20]:
torch.where((targets[:, 1] == 1) & (targets[:, 0] == 1))

(tensor([10270, 12821, 13036, 22742, 22966, 52598, 57963, 63831, 89976, 92174,
         95766]),)

In [71]:
type_adj[type_adj > 0] = 1

In [72]:
type_adj

tensor([[0., 1., 0.,  ..., 0., 0., 0.],
        [1., 0., 1.,  ..., 0., 0., 1.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.]])

In [75]:
c = 0.15

In [76]:
type_adj_sp = sp.coo_matrix(type_adj.numpy())

In [79]:
c * inv((sp.eye(type_adj_sp.shape[0]) - (1 - c) * adj_normalize(type_adj_sp)).toarray())

/home/alex/Projects/gbert/src/utils.py:11: RuntimeWarning: divide by zero encountered in power
  r_inv = np.power(row_sum, -0.5).flatten()


array([[0.16345304, 0.02429485, 0.00398539, ..., 0.00632735, 0.00350053,
        0.00606842],
       [0.02429485, 0.2080718 , 0.01876887, ..., 0.01489574, 0.00959789,
        0.02190531],
       [0.00398539, 0.01876887, 0.16762743, ..., 0.00734928, 0.00274249,
        0.00451467],
       ...,
       [0.00632735, 0.01489574, 0.00734928, ..., 0.17334213, 0.00622941,
        0.0046592 ],
       [0.00350053, 0.00959789, 0.00274249, ..., 0.00622941, 0.15822682,
        0.00308697],
       [0.00606842, 0.02190531, 0.00451467, ..., 0.0046592 , 0.00308697,
        0.15653276]])

In [81]:
def torch_adj_normalize(mx):
    row_sum = torch.sum(mx, dim=1)
    r_inv = row_sum.pow(-0.5)
    r_inv[torch.isinf(r_inv)] = 0
    r_mat_inv = torch.diag(r_inv)
    return r_mat_inv.mm(mx).mm(r_mat_inv)

In [82]:
c *  torch.inverse(torch.eye(type_adj.shape[0]) - (1 - c) * torch_adj_normalize(type_adj))

tensor([[0.1635, 0.0243, 0.0040,  ..., 0.0063, 0.0035, 0.0061],
        [0.0243, 0.2081, 0.0188,  ..., 0.0149, 0.0096, 0.0219],
        [0.0040, 0.0188, 0.1676,  ..., 0.0073, 0.0027, 0.0045],
        ...,
        [0.0063, 0.0149, 0.0073,  ..., 0.1733, 0.0062, 0.0047],
        [0.0035, 0.0096, 0.0027,  ..., 0.0062, 0.1582, 0.0031],
        [0.0061, 0.0219, 0.0045,  ..., 0.0047, 0.0031, 0.1565]])

In [ ]:
type_adj.to_sparse()

In [4]:
np.array([5.977113e-06,0.0052822004,9.092438e-05,1.6851257e-06,9.361878e-05,3.2236278e-07,0.0007488974,0.00013488698,1.9618899e-07,0.018594807,1.7188408e-05,0.32688075,1.40992015e-05,1.8004042e-05,5.4572414e-05,5.5238623e-05,0.76890457,0.117226526,7.921975e-06,0.002331016,0.0005544672,4.6047975e-05,1.2260855e-08,9.196277e-06,0.00013723996,3.8057183e-06,1.6712754e-06,4.1358264e-05,4.172053e-05,0.000110935034,2.2595827e-06,6.3489184e-05,7.306504e-06,2.6943617e-06,0.0019839827,0.00028403258,0.0010405247,1.0210346e-06,4.1852268e-06,0.0001996229,2.1325235e-05,7.801591e-06,2.7332856e-08,0.00028107202,8.169255e-05,3.670326e-05,2.0756616e-07,0.052710906,0.00019514127,2.6256112e-05,0.0001864587,1.2912211e-05,7.6298165e-05,0.009433192,6.559043e-05,1.9783052e-07,0.056373756,2.9929479e-06,7.183687e-08,0.0412252,0.3658614,2.618525e-06,7.920858e-06,2.8234776e-05,0.00020050476,4.722892e-06,7.3672086e-06,3.4553494e-05,7.387561e-05,1.2410587e-06,0.18297282,1.03735545e-07,2.0407546e-05,2.2295286e-05,0.019755458,0.001132958,0.00011376904,1.6049255e-05,6.0456387e-07,0.000105968196,5.01942e-05,2.655951e-06,1.2807429e-05,0.0001667483,7.104325e-05,0.020439604,2.251459e-05,0.00085680996,1.3157426e-05,1.321807e-05,0.0031058297,0.00014235447,8.9012145e-05,3.2188065e-05,0.03723815,0.00052006624,6.9430407e-06,0.00094551226,0.00010507868,0.0033861254,5.1135838e-05,4.3587625e-06]).sum()

2.043375159302546

In [8]:
np.array([7.015576e-06,0.99267286,1.8611607e-06,0.0015034898,4.738438e-05,9.299171e-11,0.018846616,5.6063545e-06,9.494341e-06,0.6763035,1.0765398e-06,0.0005674825,2.889613e-08,2.7451092e-06,2.483098e-06,1.08633905e-07,0.0017217728,2.6146545e-05,9.651045e-07,0.0010298436,2.5201261e-06,6.5940985e-06,6.0215974e-08,7.0647824e-05,0.0006935595,6.1068065e-12,3.6434664e-09,0.31692728,0.0020971927,1.5735024e-08,1.7580184e-09,3.650338e-06,2.414367e-07,1.9267853e-08,1.0588136e-05,4.417814e-08,0.000102249134,1.5194355e-07,6.408016e-06,0.0034328029,1.5064543e-07,3.465526e-07,1.822496e-10,7.8284884e-08,0.019442262,1.7165394e-05,0.0025101427,1.5655953e-05,1.7972205e-05,1.0280878e-07,0.0004168301,3.466046e-09,0.0024079713,3.5935257e-06,0.010375935,2.7532435e-05,0.0009966457,1.2025428e-06,5.3371406e-07,0.00012223404,0.00056245254,6.8199995e-07,4.0121995e-05,5.5512402e-08,1.3757324e-06,0.0003508566,1.797719e-05,9.135649e-07,3.4138097e-07,3.7471422e-05,3.4065044e-05,1.46906805e-05,9.346765e-09,8.916166e-05,0.0005133597,0.0012242921,0.00020369209,2.948968e-07,2.6345064e-09,5.622347e-08,9.6249525e-05,9.783023e-07,3.1971003e-06,2.4890489e-05,0.0011791672,0.00043470593,1.1257031e-06,1.8266783e-05,8.627515e-08,3.0830054e-07,0.00016498001,3.6658973e-06,2.364006e-06,1.4948229e-05,0.00022860778,3.4773948e-05,8.7702483e-07,2.644773e-05,3.6079568e-05,0.00027981962,8.9418384e-10,2.5950446e-06]).shape

(102,)

In [27]:
score = np.array([4.7289905e-05,0.89697355,3.992316e-05,7.657235e-05,3.7795322e-05,2.102361e-05,0.0043331804,6.545822e-05,2.7697884e-05,0.047498643,0.00015244883,0.0015115879,1.9866859e-05,0.00073225563,0.00013147088,0.00010524825,0.011941838,0.00044961434,0.00021585345,0.004435645,3.2222968e-05,9.181237e-05,0.00010736011,7.331944e-05,0.00023249107,8.273384e-05,6.1474886e-05,0.00025920902,4.5053002e-05,0.0001997255,5.116243e-05,4.341399e-05,6.031438e-05,2.384522e-06,0.00011924721,2.170212e-05,0.0004296506,5.6494253e-05,7.75355e-05,5.387055e-05,8.1070735e-05,3.0355998e-06,1.7494262e-05,3.1676478e-05,0.0013580802,0.00017757619,0.00033300713,0.00058954523,4.6462637e-06,1.41848595e-05,0.0014086653,0.000452997,0.00085717073,2.349277e-05,0.00026013644,2.4159377e-05,0.0011030458,0.00010878934,4.7047733e-06,0.00014568954,0.0019935765,0.0007089043,5.7683385e-05,1.60732e-05,7.958996e-06,0.000108255925,2.1698252e-05,0.0010178426,0.00017372172,0.00011533062,0.00020352805,4.1398514e-05,0.00024641273,8.498486e-06,0.0041206963,0.0037348226,0.00012403593,0.00010170217,0.00044789218,1.4148707e-05,1.76713e-05,2.5412306e-05,8.958279e-05,0.00032705348,0.00027830023,0.001979758,5.11495e-05,0.00013873664,2.922984e-05,0.0001337041,0.0011867797,0.0006536954,3.103546e-05,2.3641582e-05,0.0011183998,0.00079898204,0.00016509151,0.0013429174,0.00011997132,0.00018438854,5.333559e-05,6.967406e-05])

1.0000000005223

In [30]:
type_to_ind

{'-transit': 0,
 '-location': 1,
 '-god': 2,
 '-building-hotel': 3,
 '-language': 4,
 '-education-educational_degree': 5,
 '-building': 6,
 '-government-political_party': 7,
 '-geography-glacier': 8,
 '-location-city': 9,
 '-person-engineer': 10,
 '-person-artist': 11,
 '-time': 12,
 '-internet-website': 13,
 '-government-government': 14,
 '-disease': 15,
 '-person': 16,
 '-music': 17,
 '-organization-sports_league': 18,
 '-organization': 19,
 '-broadcast_network': 20,
 '-person-architect': 21,
 '-finance-stock_exchange': 22,
 '-building-restaurant': 23,
 '-organization-sports_team': 24,
 '-product-camera': 25,
 '-product-spacecraft': 26,
 '-geography-island': 27,
 '-geography-mountain': 28,
 '-software': 29,
 '-organization-fraternity_sorority': 30,
 '-person-religious_leader': 31,
 '-chemistry': 32,
 '-award': 33,
 '-play': 34,
 '-broadcast-tv_channel': 35,
 '-event': 36,
 '-biology': 37,
 '-building-hospital': 38,
 '-product-ship': 39,
 '-product-airplane': 40,
 '-building-library':

In [31]:
data_array = np.load('data/FIGER/label_emb_fasttext_102_300.npy')

In [33]:
data_array.shape

(102, 300)