In [1]:
from figer_preprocess import *

In [77]:
from numpy.linalg import inv

In [3]:
type_to_ind, ind_to_type, type_freq = load_types()
ent_to_ind, ind_to_ent, embeddings = load_embeddings()
features, targets = load_data(ent_to_ind, type_to_ind, embeddings)

Skipping entity /m/02ptrs
Skipping entity /m/03psd
Skipping entity /m/05b6ds
Skipping entity /m/0h1cfg
Skipping entity /m/0265gs


In [9]:
targets[targets==0] = -1

In [10]:
targets = torch.tensor(targets, dtype=torch.float)
type_adj = batched_target_to_adj(targets)

In [11]:
type_adj = torch.sum(type_adj, dim=0)

In [20]:
torch.where((targets[:, 1] == 1) & (targets[:, 0] == 1))

(tensor([10270, 12821, 13036, 22742, 22966, 52598, 57963, 63831, 89976, 92174,
         95766]),)

In [71]:
type_adj[type_adj > 0] = 1

In [72]:
type_adj

tensor([[0., 1., 0.,  ..., 0., 0., 0.],
        [1., 0., 1.,  ..., 0., 0., 1.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.]])

In [75]:
c = 0.15

In [76]:
type_adj_sp = sp.coo_matrix(type_adj.numpy())

In [79]:
c * inv((sp.eye(type_adj_sp.shape[0]) - (1 - c) * adj_normalize(type_adj_sp)).toarray())

/home/alex/Projects/gbert/src/utils.py:11: RuntimeWarning: divide by zero encountered in power
  r_inv = np.power(row_sum, -0.5).flatten()


array([[0.16345304, 0.02429485, 0.00398539, ..., 0.00632735, 0.00350053,
        0.00606842],
       [0.02429485, 0.2080718 , 0.01876887, ..., 0.01489574, 0.00959789,
        0.02190531],
       [0.00398539, 0.01876887, 0.16762743, ..., 0.00734928, 0.00274249,
        0.00451467],
       ...,
       [0.00632735, 0.01489574, 0.00734928, ..., 0.17334213, 0.00622941,
        0.0046592 ],
       [0.00350053, 0.00959789, 0.00274249, ..., 0.00622941, 0.15822682,
        0.00308697],
       [0.00606842, 0.02190531, 0.00451467, ..., 0.0046592 , 0.00308697,
        0.15653276]])

In [81]:
def torch_adj_normalize(mx):
    row_sum = torch.sum(mx, dim=1)
    r_inv = row_sum.pow(-0.5)
    r_inv[torch.isinf(r_inv)] = 0
    r_mat_inv = torch.diag(r_inv)
    return r_mat_inv.mm(mx).mm(r_mat_inv)

In [82]:
c *  torch.inverse(torch.eye(type_adj.shape[0]) - (1 - c) * torch_adj_normalize(type_adj))

tensor([[0.1635, 0.0243, 0.0040,  ..., 0.0063, 0.0035, 0.0061],
        [0.0243, 0.2081, 0.0188,  ..., 0.0149, 0.0096, 0.0219],
        [0.0040, 0.0188, 0.1676,  ..., 0.0073, 0.0027, 0.0045],
        ...,
        [0.0063, 0.0149, 0.0073,  ..., 0.1733, 0.0062, 0.0047],
        [0.0035, 0.0096, 0.0027,  ..., 0.0062, 0.1582, 0.0031],
        [0.0061, 0.0219, 0.0045,  ..., 0.0047, 0.0031, 0.1565]])

In [ ]:
type_adj.to_sparse()

tensor(indices=tensor([[  0,   0,   0,  ..., 101, 101, 101],
                       [  1,   6,  19,  ...,   9,  19,  75]]),
       values=tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                      1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
                  